<a href="https://colab.research.google.com/github/khanapujiyanti/PSDS_3.0_KelasDasar/blob/main/M4P1V1_Operasi_NumPy_dan_Matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Array

NumPy merupakansalah satu library Python yang banyak digunakan dalam proses analisis data karena fiturnya yang hebat.

In [1]:
import numpy as np

#Membuat Array Numpy

Kita bisa membuat array menggunakan NumPy dengan membungkusnya terlebih dahulu di List dan dirubah menjadi numpy array.

In [2]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

Beberapa fungsi yang dapat digunakan dalam membuat array

```
zeros() -> membuat array dengan nilai 0

ones()  -> membuat array dengan nilai 1

arange() -> membuat array dengan nilai dalam range

linspace -> membuat array dengan nilai dalam interval

logspace -> membuat array dengan nilai log Base10 dalam interval

full -> membuat array dengan semua elemen penyusunnya sama

full_like -> membuat array dengan smua elemen penyusunnya sama namun ukurannya dari array lainnya

identity -> membuat array matriks identitas

repeat  -> membuat array dengan perulangan array atau sequence
```

In [3]:
print(np.zeros((2,5))) #membuat array dengan nilai 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
print(np.ones((5,3))) # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.arange(1, 10, 2)) #arange(start, stop, step)

[1 3 5 7 9]


In [6]:
print(np.linspace(1, 10, 2)) #linespace(star, stop, number)

[ 1. 10.]


In [7]:
print(np.logspace(1,10,2)) #logspace(start, stop, number)

[1.e+01 1.e+10]


In [8]:
print(np.full((2,2),4)) #Membuat array matriks dengan shape (2,2) dengan elemen 99

[[4 4]
 [4 4]]


In [9]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A,3)) # Membuat array matriks dengan shape yang sama dengan A semua elemen 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [10]:
print(np.random.rand(4,2)) #Random decimal number

[[0.32516294 0.34640124]
 [0.81820668 0.34907759]
 [0.12965007 0.06209036]
 [0.26548106 0.73594758]]


In [11]:
print(np.random.randint(-4,8, size=(3,3))) #Random integer values

[[1 7 1]
 [7 1 2]
 [1 3 3]]


In [12]:
print(np.identity(5)) #Membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
arr = np.array([[1,2,3]]) #membuat matriks dengan perulangan array
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#Metode-metode pada array

Objek array pada Python Numpy memiliki berbagai method untuk melakukan operasi atau perintah-perintah tertentu. Berikut adalah fungsi-fungsiyang merupakan metode pada array yang sering dipakai:

 **array.ndim**

Metode ini digunakan untuk mengetahui dimensi dari array.

In [14]:
a=np.array([29, 28, 30], dtype='int32')
print(a)

print("Dimensi dari array a adalah ", a.ndim)

[29 28 30]
Dimensi dari array a adalah  1


**array.shape**

Metode ini digunakan untuk mengetahui ukuran (variabel dan baris) dari array.

In [19]:
b = np.array([[9,.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

print("Ukuran Shape dari array b adalah ", b.shape)

[list([9, 0.0, 8.0, 7.0]) list([6.0, 5.0, 4.0])]
Ukuran Shape dari array b adalah  (2,)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


**array.dtype**

Metode ini digunaka untuk mengtahui type data dari elemen penyusun array.

In [20]:
a.dtype

dtype('int32')

**array.size**

Merode ini digunakan untuk menghitung jumlah elemen dari array.

In [21]:
a.size

3

#Multidimensional Array

Salah satu fitur menarik dari NumPy adalah dia mampu membuat multidimensional array dan melakukan manipulasi array dengan mudah dan cepat

Multidimensional array adalah array yang berbentuk lebih dari 1 dimensi (1D), bisa 2D, 3D, 4D dan seterusnya

Cara membuat multidimensional array sama dengan membuat array 1 dimensi, perbedaannya hanya pada parameter yang digunakan

Berikut contohnya membuat array 2 dimensi

In [22]:
arr_2 = np.array([[1,2,3,4,5], [2,4,6,8,10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

Array diatas adalah berbentuk (2,5) artinya mempunyai 2 baris dan 5 kolom 

Kita bisa melihat jumlah elemen di setiap dimensi dengan menggunakan shape

In [23]:
arr_2.shape

(2, 5)

#Indexing dan Slicing



Kita juga dapat melakukan indexing dan slicing terhadap array dengan mudah

Indexing dimulai dari 0 dan dimulai dengan notasi bracket"[]"

Misal kita ingin mencari nilai yang berada di index 0, 2, dan 4

In [24]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0])
print(arr_3[2])
print(arr_3[4])

1
3
5


Untuk mengambil nilai bederet tambahkan ":"

In [25]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0:4])

[1 2 3 4]


In [28]:
arr_4 = np.array([[1,2,3,4,5],[2,4,6,8,10]])
print(arr_4)
print(arr_4[1:3])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
[[ 2  4  6  8 10]]


Nilai pada kolom index ke-1 dan baris indx ke-1 adalah 4

#Operasi Aritmatika


Kita bisa menggunakan operasi aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian dan perpangkatan

Operator yang digunakan adalah +,-,,/dan*

Berikut contoh operasi aritmatika array

In [29]:
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([2,2,2,2,2])

print("Penjumlahan =", arr_A + arr_B)
print("Pengurangan = ", arr_A - arr_B)
print("Perkalian = ", arr_A * arr_B)
print("Pembagian = ", arr_A / arr_B)
print("Perpangkatan = ", arr_A ** arr_B)

Penjumlahan = [3 4 5 6 7]
Pengurangan =  [-1  0  1  2  3]
Perkalian =  [ 2  4  6  8 10]
Pembagian =  [0.5 1.  1.5 2.  2.5]
Perpangkatan =  [ 1  4  9 16 25]


#operasi Matematika


NumPy mempunyai fungsi matematika yang dapat digunakan pada array

Beberapa contoh fungsi statistik antara lain min(),max(), mean(), sum(), std()

In [30]:
arr_5 = np.array([1,2,3,4,5])
print("Nilai minimal = ", arr_5.min())
print("Nilai maksimal = ", arr_5.max())
print("NIlai rata-rata = ", arr_5.mean())
print("Total nilai = ", arr_5.sum())
print("Standar Deviasi = ", arr_5.std())

Nilai minimal =  1
Nilai maksimal =  5
NIlai rata-rata =  3.0
Total nilai =  15
Standar Deviasi =  1.4142135623730951


Ada juga fungsi argmin() dan argmax() untuk mendapatkan indeks dari nilai minimum dan maksimum

In [31]:
print("Index nilai minimal = ", arr_5.argmin())
print("Index nilai maksimal = ", arr_5.argmax())

Index nilai minimal =  0
Index nilai maksimal =  4


#Transformasi Array

Kita dapat membuat array baru dari array yang sudah ada melalui berbagai metode transformasi seperti merubah ukuran, menggabungkan dua array atau lebih dan lain sebagainya

**array.reshape**

metode ini digunakan untuk merubah shape array dengan jumlah elemen yang tidak berubah.

In [32]:
sebelum = np.array([[1,2,3,4],[5,6,7,8]])
print(sebelum)

sesudah = sebelum.reshape((8,1))
print(sesudah)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


Perhatikan bahwa array ```sebelum``` memiliki jjumlah elemen 8(2,4) dan array ```sesudah``` memiliki jumlah elemen8 (4,2).

**array.vstack**

Metode ini dilakukanuntuk menumpuk beberapa array secara vertikal

In [35]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

**array.hstack**

Metode ini dilakukan untuk menumpuk beberapa array secara horizontal.

In [36]:
h1 = np.array([2,4])
h2 = np.array([2,2])
print(h1)
print(h2)

print(np.hstack((h1,h2)))

[2 4]
[2 2]
[2 4 2 2]


#Representasi Matriks Pada Python

Matriks adalah array 2 dimensi khusus yang memperhatikan sifat 2 dimensinya melalui operasi. Matriks memiliki operator khusus tertentu, seperti perkalian matriks dan pemangkatan matriks.

Berikut adalah beberapa penlisan python di berbagai platform:



Berikut contoh penulisan matriks pada python:

In [37]:
import numpy as np

In [38]:
A = np.array([[1,2],[4,5]])
A

array([[1, 2],
       [4, 5]])

In [39]:
B = np.array([[1,2,3], [4,5,6],[7.8,9]])
B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([4, 5, 6]), list([7.8, 9])], dtype=object)

#Operasi Matriks Pada Python

In [40]:
P = np.array([[1,2],[4,5]])
P

array([[1, 2],
       [4, 5]])

In [41]:
Q = np.array([[7,8],[9,10]])

In [42]:
a = 29
a

29

**Penjumlahan Matriks**

In [43]:
np.add(P,Q)

array([[ 8, 10],
       [13, 15]])

**Pengurangan  Matriks**

In [44]:
np.subtract(P,Q)

array([[-6, -6],
       [-5, -5]])

**Perkalian Skalar Matriks**

In [45]:
a*P

array([[ 29,  58],
       [116, 145]])

**Perkalian matriks**

In [46]:
np.multiply(P,Q)

array([[ 7, 16],
       [36, 50]])

**Perkalian Titik Matriks (Dot Product)

In [47]:
np.dot(P,Q)

array([[25, 28],
       [73, 82]])

**Transpose Matriks**

In [48]:
P.T

array([[1, 4],
       [2, 5]])

**Operasi Fungsi Pada Setiap Elemen Matriks-Akar Kuadrat** 

In [49]:
np.sqrt(P)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

**Menjumlahkan Semua ELemen kolom Sebuah Matriks**



In [50]:
Q

array([[ 7,  8],
       [ 9, 10]])

In [51]:
 np.sum(Q,axis=1)

array([15, 19])

**Menjumlahkan Semua Elemen Baris Sebuah Matriks**

In [52]:
np.sum(Q, axis=0)

array([16, 18])

#Aljabar Linear Pada Python

Dalam modul numpy juga disediakan fungsi-fungsi Aljabar untuk matriks. Beberapa konsep Aljabar Linear yang akan di tunjukan di modul ini adalah

* Determinan
* INVerse
* Nilai eigen
* Vaktor eigen
* Matriks identitas
* Matriks Satuan
* Matriks nol
* Matriks segitiga L dan U
* Dekomposisi L U matriks

In [54]:
A = np.array([[2,3,4], [7,8,9],[10,7,8]])
A

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [10,  7,  8]])

In [55]:
B=np.array([[5,7,4],[6,8,9],[1,2,6]])
B

array([[5, 7, 4],
       [6, 8, 9],
       [1, 2, 6]])

**Determinan**

In [56]:
np.linalg.det(A)

-20.000000000000007

**Inverse Matriks**

In [57]:
np.linalg.inv(A)

array([[-0.05, -0.2 ,  0.25],
       [-1.7 ,  1.2 , -0.5 ],
       [ 1.55, -0.8 ,  0.25]])

**Nilai Eigen dan Vector Eigen**

In [58]:
eig, vec_eig= np.linalg.eig(A)
print('Nilai eigen matriks A:')
print(eig)
print('vektor eigen matriks:')
print(vec_eig)

Nilai eigen matriks A:
[19.39079317 -1.9262474   0.53545423]
vektor eigen matriks:
[[-0.27295093 -0.54761756  0.15754422]
 [-0.6940728  -0.31621014 -0.8168342 ]
 [-0.66615369  0.7746781   0.55494297]]


**Matriks Identitas**

In [60]:
Identitas=np.identity(5)
print(Identitas)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [61]:
Identitas[:,3]

array([0., 0., 0., 1., 0.])

**Matriks Satuan**

In [62]:
Satuan=np.ones((2,3))
Satuan

array([[1., 1., 1.],
       [1., 1., 1.]])

**Matriks Nol**

In [64]:
MatriksNol=np.zeros(10)
MatriksNol

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Matriks Segitiga Atas dan Bawah

In [66]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
Lower=np.tril(M, -1)
Lower

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [68]:
Upper=np.triu(M, 1)
Upper

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

Matriks Dekompsisi LU

In [69]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

P, L, U =la.lu(A)
print(P)

print(L)

print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.7        1.         0.        ]
 [0.2        0.51612903 1.        ]]
[[10.          7.          8.        ]
 [ 0.          3.1         3.4       ]
 [ 0.          0.          0.64516129]]


#Membangun Matriks Menggunakan Perulangan

In [70]:
C=np.arange(0,10,1)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
C**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
L=[]
for i in C:
  L.append(i+1)
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
A=np.zeros([3,4])
baris, kolom = np.shape(A)
print(baris)
print(kolom)
print(A)
arr=[]
for i in range(baris):
  arr.append([])
  print(arr)
  for j in range(kolom):
    arr[i].append((i+j)*2)
    print(arr)
print(np.array(arr))

#Latihan

1. Buatlah array matriks identitas dengan ukuran 20x20!

In [74]:
A=np.identity(20)
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

2. Buatlah array matriks dengan ukuran sesuai dengan array c dan dengan elemennya adalah bilangan 112!

```c=[20, 60, 50, 70, 90, 78, 46, 56]```

In [76]:
c = np.array([20,60,50,70,90,78,46,56])
print(np.full_like(c, 112))

[112 112 112 112 112 112 112 112]
